# Generated by Django 5.2.1 on 2025-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_creacion_usuario', '0004_imagen_sig_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
                ('fuente', models.CharField(max_length=255)),
                ('fecha_subida', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('validado_por', models.CharField(max_length=255)),
            ],
        ),
    ]
