# Generated by Django 5.2.1 on 2025-06-13 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_creacion_usuario', '0005_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='comentario',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En revisión'), (2, 'Aprobado'), (3, 'Rechazado')], default=1),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_actualizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_subida',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='validado_por',
            field=models.CharField(default='Ninguno', max_length=255),
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table='solicitud',
        ),
    ]
